### ISSUE TITLE
Fix the Bevy Renet example!

### ISSUE THREAD

**Issue by Oglo12** [lucaspoffo/renet#110]
The Bevy Renet example doesn't compile! I would love it if you showed what the Cargo.toml should look like, and fix the thing where you try to import `renet::ClientId`, but that doesn't exist!

**Comment by SwordOfDamocles** [comment]
Yeah, I'd like to second this issue...Super-stoked about using Renet for my project, but I was trying to work my way through the examples in the root README.md, as well as the demos, and there seem to be quite a few things that are out of date now.

**Comment by lucaspoffo** [comment]
If you are using the the last released version you can get the correct examples in:
https://github.com/lucaspoffo/renet/tree/0.0.13

The examples in the main branch requires to use the last commit to compile. Also the README need some small fixes
