### ISSUE TITLE
Doesn't seem to connect on a non-localhost connection

### ISSUE THREAD

**Issue by Aceeri** [lucaspoffo/renet#12]
Heyo! I'm still digging into this but I think there might be an issue with how the UDP socket receives/sends if the server is not bound to `127.0.0.1`.

Just wanted to make this for some visibility, but I'm going to look more into it. Will update this as I figure out more.

I made this repo to just test a raw udp socket: https://github.com/Aceeri/udp-screech and that seems to work fine, but copy pasting the udp socket code from that to the bevy_renet example doesn't seem to.

**Comment by Aceeri** [comment]
The server does seem to be receiving packets.

**Comment by Aceeri** [comment]
Ah was just this:
```rust
let in_host_list = connect_token.server_addresses.iter().any(|host| *host == Some(self.address));
if !in_host_list {
    return Err(NetcodeError::NotInHostList);
}
```
The connect address is the public ip but the host address is the local ip.

**Comment by Shatur** [comment]
Faced the same issue. It would be nice to be able to disable this check.

**Comment by Aceeri** [comment]
Gotcha yeah, @Shatur is correct, on the server have to make sure the server ip is actually set to the public ip, while the UdpSocket is connected to the local one.
