### ISSUE TITLE
Error: linking with `cc` failed: exit status: 1

### ISSUE THREAD

**Issue by nickacide** [lucaspoffo/renet#122]
Hi, I've run into [this error](https://gist.github.com/nickacide/b0c6cdaaafe9565566baab192810ae8b) when trying out some [demo code](https://gist.github.com/nickacide/7fe44c149a3e6eb8a8fe7a197a7604f8). Note: both the client and server code produced this error.

It's a pretty nasty error to encounter for the first time so I tried a few things:
- since I was using mold linker I tried the `lld` linker 
- I ran `cargo clean` and `cargo run` 
- I tried reinstalling rust with a different version according to [this SO post](https://stackoverflow.com/a/70310934)
- I have not tried this on a different machine yet, will do so tomorrow (using Ubuntu which I installed a few days ago). Then I'll also try some extra examples to see if the results are reproduced

I am quite certain that `bevy_renet` is involved in the error since compiling a file without it works fine. 
If you need any more details let me know.

**Comment by lucaspoffo** [comment]
Are you still having this problem? Do the bevy examples work fine for you?
