### ISSUE TITLE
Upgrade `bevy_renet` to `bevy 0.12`

### ISSUE THREAD

**Issue by ActuallyHappening** [lucaspoffo/renet#124]
Thanks for this awesome ecosystem of crates!
Unfortunately, `bevy_renet` is blocking `bevy_replicon` from upgrading to `bevy 0.12`. I'll try to upgrade `bevy_renet`, is there anything I should know?

**Comment by solnyszczko** [comment]
i like it too please update pretty please

**Comment by ostwilkens** [comment]
This was very easy to upgrade. Highly recommend sending PR:s to update your favourite plugins :-)
https://github.com/lucaspoffo/renet/pull/125

**Comment by ActuallyHappening** [comment]
Thanks for the PR @ostwilkens :)

**Comment by lucaspoffo** [comment]
Fixed it in fb71a405deaf2f90c8d5f609c0e40f5a594beacf
I will keep this issue open until the new version with it is actually released (prob tomorrow)

**Comment by raffaeleragni** [comment]
Is release coming right?

**Comment by raffaeleragni** [comment]
Reminder of pending release
