### ISSUE TITLE
Bug: client does not disconnect cleanly.

### ISSUE THREAD

**Issue by UkoeHB** [lucaspoffo/renet#133]
After calling `RenetClient::disconnect()`, the method `RenetClient::is_connecting()` returns true.

**Comment by lucaspoffo** [comment]
Can you show a small example that replicates this behavior? I was not able to make a simple reproduction case, for example, this simple case is working:

```rust
let mut connection = RenetClient::new(ConnectionConfig::default());
assert!(connection.is_connecting());
connection.disconnect();
assert!(!connection.is_connecting());
```
