### ISSUE TITLE
Client vs server timeout

### ISSUE THREAD

**Issue by UkoeHB** [lucaspoffo/renet#135]
When creating a connect token, the server timeout is passed in via `ConnectToken::generate()`, while the client timeout is implicitly set to `NETCODE_TIMEOUT_SECONDS`. From what I can tell in the netcode spec, the client timeout is meant to be configurable.

`ConnectToken::generate()` should also take in the client timeout. One workaround is to manually edit the connect token struct, since the fields are now `pub`.

**Comment by lucaspoffo** [comment]
Fixed in 9add0a326098f69a6a7489554c05f85dbec8c530
