### ISSUE TITLE
Add bevy_renet to assets list

### ISSUE THREAD

**Issue by NiklasEi** [lucaspoffo/renet#16]
I just learned about renet via the Bevy discord. It would be helpful to see `bevy_renet` on https://bevyengine.org/assets/#networking.
This can be done in a PR to https://github.com/bevyengine/bevy-assets.

**Comment by lucaspoffo** [comment]
I'll take a look to add it :+1:

**Comment by lucaspoffo** [comment]
Closed by https://github.com/bevyengine/bevy-assets/pull/230
