### ISSUE TITLE
Update to bevy 0.15

### ISSUE THREAD

**Issue by aekobear** [lucaspoffo/renet#166]
Latest bevy just dropped. Working on a PR right now

edit: waiting on `smooth-bevy-cameras` to [be updated](https://github.com/bonsairobo/smooth-bevy-cameras/issues/49) before renet can be updated

**Comment by Preston-Harrison** [comment]
Looks like it's been updated

**Comment by Luminoth** [comment]
The commit to update for 0.15 went in 2 weeks ago, is there any reason a release can't be cut so folks can get their dependent projects updated?

**Comment by tsal** [comment]
> Looks like it's been updated

It has been in the branch, but the crate itself has not been released with a new version. This means folks are forced to use a git branch / hash to use the updated imports.

**Comment by tsal** [comment]
just realized @Preston-Harrison meant `smooth-bevy-cameras`, and not this repo. and yes, a release would be nice.

**Comment by adrylain** [comment]
I believe the crates.io is not up to date btw

**Comment by raffaeleragni** [comment]
bevy_renet on master seems still to 0.0.12 on Cargo.toml? https://github.com/lucaspoffo/renet/blob/master/bevy_renet/Cargo.toml#L9

**Comment by LucaCoduriV** [comment]
Hello, any news about it ?

**Comment by Luminoth** [comment]
I gave up waiting and forked the dependencies I need with that git redirect. It works fine so we're just sort of stuck with workarounds until they cut the release.

**Comment by lucaspoffo** [comment]
Done with 1.0 release:
https://github.com/lucaspoffo/renet/releases/tag/1.0.0
