### ISSUE TITLE
Add an option to disable connection token verification

### ISSUE THREAD

**Issue by Alainx277** [lucaspoffo/renet#29]
While testing my game, I don't care about security configurations, and just want other people to be easily able to join.
I've also noticed the case in #12, and would like to be able to bypass it in development.

**Comment by lucaspoffo** [comment]
Closed by e635b819123d7c90ea7c4a59d79af7660ec0c0df

On all examples/demos we are using unsecure connections, making this a configuration helps clean up the code and make clear it is not secure, and makes it simpler to establish connections when testing/prototyping.

To showcase on how to establish secure connections I'll probably update the chat/bevy demo with a simple matchmaking service.
