### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by DogsCodesStudio** [lucaspoffo/renet#33]
The simple example doesn't work in bevy example file

```
    RenetClient::new(current_time, socket, client_id, connection_config, authentication).unwrap()
``` 
renet client should be like this having 5 arguments instead of 4.

**Comment by dennym** [comment]
For the sake of adding also a solution to it and not let everyone figure it out themselfs.... 
Check the tag `0.0.9` which has a slight different approach.
https://github.com/lucaspoffo/renet/blob/0.0.9/demo_bevy/src/bin/client.rs
