### ISSUE TITLE
Return an iterator from clients_id

### ISSUE THREAD

**Issue by Shatur** [lucaspoffo/renet#47]
Currently `RenetServer::clients_id()` returns `Vec` but it's not very flexible and users usually wants to iterate over them in most cases. So I would suggest to return `impl Iterator` instead.

**Comment by lucaspoffo** [comment]
The problem with returning an iterator is that it would keep a reference to RenetServer, so we would not be able to call:
```rust
// This would need to be server.clients_id().collect().into_iter() {
for client_id in server.clients_id() {
   while let Some(message) = server.receive_message(client_id, channel_id) {
       // ...
   }
}
```

I could return an owned iterator by creating a new Vec and returning an iterator over it, but at this point, why not just return the Vec. Could also implement a new function just for the iterator I guess. 

There might be a better way, not sure

**Comment by Shatur** [comment]
Right, it won't work because of the borrow checker :(
Better keep as is then.

**Comment by Shatur** [comment]
Although, maybe add `iter_client_ids()` for iteration-only cases?

**Comment by lucaspoffo** [comment]
Added in #91
