### ISSUE TITLE
Two clients disconnecting without sending `client.disconnect()` breaks renet

### ISSUE THREAD

**Issue by MasterOfMarkets** [lucaspoffo/renet#68]
Renet breaks when two clients disconnect without using the proper `client.disconnect()` function and a new client subsequently connects. 
I have included a video demonstrating running the demo_bevy.

One potential cause of this issue could be that all of the clients and the host have the same IP address.

Important to note: I´m exiting the client with `ctrl+C`, witch causes the client to exit with sending `client.disconnect()`.

https://user-images.githubusercontent.com/51098127/210580106-a30edbd8-76a5-4a96-8f00-8089bd771e8c.mp4

**Comment by MasterOfMarkets** [comment]
This is probably related to https://github.com/lucaspoffo/renet/issues/63#issue-1474803207

**Comment by lucaspoffo** [comment]
Fixed by https://github.com/lucaspoffo/renet/pull/82
Tested using Windows, doing the same steps as the GIF and no problem occurred
