### ISSUE TITLE
Limit syncing?

### ISSUE THREAD

**Issue by tigerplush** [lucaspoffo/renet#70]
Hey,

I'm currently just trying out your library and it is amazing, thank you - but I've run into an issue:

I'm sending a transform to the server over the Default UnreliableChannel who then sends it back to every player. Within seconds, even with one player, messages get dropped - could you point me in the direction as to why that is?

**Comment by lucaspoffo** [comment]
Hey,

Is the server using the MinimalPlugin instead of the DefaultPlugins? When you use this option, the server run at an unlimited frame rate, you need to add the scheduler settings with:
```
 .insert_resource(ScheduleRunnerSettings::run_loop(Duration::from_secs_f64(
            1.0 / 60.0,
 )))
.add_plugins(MinimalPlugins)
```

Make sure the resource is inserted before the plugin

**Comment by tigerplush** [comment]
Sadly that didn't help :/

warning is
`WARN rechannel::channel::unreliable: Received message was dropped in unreliable channel 1, reached maximum number of messages 256`

my main looks like this:
```Rust
    App::new()
        .insert_resource(Players::new())
        .insert_resource(ScheduleRunnerSettings::run_loop(Duration::from_secs_f64(
            1.0 / 60.0,
        )))
        .add_plugins(MinimalPlugins)
        .add_plugin(LogPlugin::default())
        .add_plugin(AssetPlugin::default())
        .add_plugin(ServerPlugin)
        .run();
```

**Comment by tigerplush** [comment]
I'm silly, I didn't iterate over `receive_message()`, when I do that it works

**Comment by tigerplush** [comment]
as soon as I add
```Rust
        while let Some(raw_message) = server.receive_message(client_id, DefaultChannel::Unreliable) {
        }
```
The server can keep up
