### ISSUE TITLE
`ConnectionReset` breaks `RenetServer::update()`

### ISSUE THREAD

**Issue by gerdoe-jr** [lucaspoffo/renet#76]
On Windows, `update()` will throw `Os { code: 10054, kind: ConnectionReset, message: "An existing connection 
was forcibly closed by the remote host." }` if client forced connection closing (e.g, client crashed without sending disconnect packet).

**Comment by arseeeeN** [comment]
I have the same issue on my machine (Windows). Renet doesn't seem to recognize clients that disconnect this way and will send error events every frame in bevy.

**Comment by lucaspoffo** [comment]
Fixed by bf49592f221eee7853abd22314a33ee3d1f81690
The server now handles this error.
