### ISSUE TITLE
Add helper to receive last message

### ISSUE THREAD

**Issue by Shatur** [lucaspoffo/renet#80]
When you working with unreliable sequenced channel you sometimes want to receive only the last message. Currently I have to call `receive_message` manually until it returns `false` which is not very ergonomic.

**Comment by lucaspoffo** [comment]
There is no option for sequenced channels anymore, so this auxiliary function doesn't make a lot of sense now.

For unreliable sequenced messages, the user must implement it.
This could be done by adding a `sequenced_id` to the unreliable messages and keeping track of it - dropping messages below the sequenced value.
