### ISSUE TITLE
Add connection and disconnection events for client

### ISSUE THREAD

**Issue by Shatur** [lucaspoffo/renet#94]
We have connection event for server, it would be very convenient to have a similar feature for client. We currently have conditions for checking states, but there is no way to check if client "just" connected. We could provide additional conditions for it too, but events for this case would be more idiomatic.

**Comment by lucaspoffo** [comment]
Events for clients will not be added.
But, with bevy_renet, we can now use run conditions - `client_just_connected`, `client_just_disconnected` - added in #96 for similar effect :+1:
